eureka.fetch.seconds: 120
aggregator.eureka.enabled: true
params.restTemplateConfiguration.enabled: true
swagger-params.enabled: true

#local
params:
  eureka:
    uri: http://localhost:8761/eureka/
  oauth2:
    issuerUri: http://localhost:8764
  gatewayOauth2:
    uri: http://SPRINGBOOT-CONF-GATEWAY-API-OAUTH2
  swaggerAggregator:
    uri: http://localhost:8766
  zipkin:
    uri: http://localhost:9411
  keystore:
    type: PKCS12
    path: file:C:/E/TOOLS/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: C:/E/TOOLS/ms1-truststore.jks
    password: jihed1234
######################################################
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    display-request-duration: true
  extraScripts:
    - /static/custom-swagger.js

swagger-params:
  issuerUri: ${params.oauth2.issuerUri}
  servers:
    liste:
      - uri: http://localhost:${server.port}
        description: Local environment
      - uri: http://10.0.0.137:${server.port}
        description: Development environment
      - uri: http://10.0.0.500:${server.port}
        description: Homologation environment
      - uri: http://10.0.0.500:${server.port}
        description: Production environment
  aggregator:
    enabled: ${aggregator.eureka.enabled:false}
    cors:
      uri: ${params.swaggerAggregator.uri}
######################################################
caller:
  destination:
    # gr-conf-swagger-aggregator from swagger.
    client0:
      resourceUri:
      clientId:
      clientSecret:
      scopes:
      registrationId: