aggregator.eureka.enabled: false

###################################################################
#dev
params:
  eureka:
    uri: http://container-gr-eureka-server:8761/eureka/
  oauth2:
    issuerUri: http://container-gr-auth-server:8764
  gatewayOauth2:
    uri: http://GR-API-GATEWAY
  swaggerAggregator:
    uri: http://container-gr-conf-aggregator-server:8765
  zipkin:
    uri: http://container-zipkin:9411
  keystore:
    type: PKCS12
    path: file:/certificates/ms2.p12
    password: jihed123
    alias: ms2
  truststore:
    path: /certificates/ms1-truststore.jks
    password: jihed1234