server:
  port: 1204

spring:
  application:
    name: gr-resource-consumer-webclient

  security:
    oauth2:
      client:
        registration:
          consumer-webclient:
            client-id: gr-resource-consumer-webclient
            client-secret: consumer-webclient
            scope: ms1.read,ms2.read
            authorization-grant-type: client_credentials
            provider: gr-auth-server
        provider:
          gr-auth-server:
            token-uri: http://localhost:8764/oauth2/token

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web.exposure.include: "*"
    web.base-path: /actuator
    web.enable.include: health
  endpoint:
    health:
      show-details: ALWAYS