server.port: 7766

spring:
  application:
    name: gr-api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:

# gr-oauth2-demo
        - id: gr-ms1-resource
          uri: lb://GR-MS1-RESOURCE
          predicates:
            - Path=/ms1/**
          filters:
            - StripPrefix=1
        - id: gr-ms2-resource
          uri: lb://GR-MS2-RESOURCE
          predicates:
            - Path=/ms2/**
          filters:
            - StripPrefix=1
        - id: gr-ms3-resource
          uri: lb://GR-MS3-RESOURCE
          predicates:
            - Path=/ms3/**
          filters:
            - StripPrefix=1

# gr-oauth2-swagger-demo
        - id: gr-oauth2-swagger-ms1
          uri: lb://GR-OAUTH2-SWAGGER-MS1
          predicates:
            - Path=/ms4/**
          filters:
            - StripPrefix=1
        - id: gr-oauth2-swagger-ms2
          uri: lb://GR-OAUTH2-SWAGGER-MS2
          predicates:
            - Path=/ms5/**
          filters:
            - StripPrefix=1

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${params.oauth2.issuerUri}
########################################################
eureka:
  client:
    enabled: true
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: ${eureka.fetch.seconds:25}
    service-url:
      defaultZone: ${params.eureka.uri}
  instance:
    preferIpAddress: true
    #----> Remove ipAddress and hostname to let Eureka resolve dynamically
    #ipAddress: ${host.where.docker.ip}
    #----> Optionally, set a non-qualified hostname if needed
    #hostname: ${spring.application.name}
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
      #----> Indique que ce microservice doit être inclus dans le swagger de 'gr-conf-swagger-aggregator'
      #----> (désactivé par défaut sinon).
      swagger.aggregator.enabled: ${aggregator.eureka.enabled:false}
      management.context-path: /actuator

management:
  endpoints:
    web.exposure.include: "*"
    web.base-path: /actuator
    web.enable.include: health
  endpoint:
    health:
      show-details: ALWAYS
  # --> Include git.properties generated informations (plugin:git-commit-id-plugin) in /actuator/info endpoint.
  info:
    git:
      mode: full